---
all:
  children:
    csr_routers:
      vars:
        ansible_connection:           ansible.netcommon.network_cli
        ansible_network_os:           cisco.ios.ios
        ansible_network_cli_ssh_type: libssh
        ansible_host_key_checking:    false
        ansible_command_timeout:      100
        ansible_connect_timeout:      100
      hosts:
        ZUSE1P2GBSSSVPN001:
        ZUSE1P2GBSSSVPN002:
        ZUSSCGBSPCISCO1:
        ZUSSCGBSPCISCO2:
